### ISSUE TITLE
Remove checklist tooling

### ISSUE THREAD

**Issue by peterdesmet** [frictionlessdata/frictionless-r#206]
Remove tooling added by [checklist](https://github.com/inbo/checklist) package:

- [x] `Config/checklist/communities: inbo` in DESCRIPTION
- [x] `Config/checklist/keywords` in DESCRIPTION
- [x] `Language: en-GB` in DESCRIPTION
- [x] `checklist.yml`: is yet another file to maintain, in addition to `codemeta.json` and `CITATION.cff`
- [x] `zenodo.json`: most of the metadata is understood by Zenodo through `CITATION.cff`
  - [ ] Title = `citation.title`
  - [ ] Authors = `citationauthors`: Names and ORCIDs ok, need to figure out affiliation
  - [ ] Description = Release description
  - [ ] Notes = `citation.message`
  - [ ] Keywords = `citation.keywords`
- [x] `codecov.yml`
